on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 15 * * 1'
name: build via dagger
jobs:
  build:
    runs-on: [ubuntu-latest]
    services:
      registry:
        image: registry
        ports:
          - 15000:5000
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare dagger and test environment
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            project init
            project update
      - name: Build image and push to local registy
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            do build
            do push
        env:
          PUSH_IMAGE: localhost:15000/testing-image
      - name: Execute e2e test
        run: |
          cd e2e; docker-compose run e2e
      - name: Build image and push to local registy
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            do build
            do push
        env:
          PUSH_IMAGE: localhost:15000/testing-image
      - name: Log in to Docker Hub
        uses: docker/login-action:v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image and push to local registy
        uses: dagger/dagger-for-github@v3
        with:
          cmds: |
            do build
            do push
        env:
          PUSH_IMAGE: knaou/mkdocs-uml
      - name: Archive build output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-report
          path: |
            !.gitignore
            _build/**/*
